version: "3.7"

services:
  ############################################## GPU containers##############################################################
  tensorflow-jupyter-gpu-manish:
    container_name: tjg-1-manish
    build:
      context: .
      dockerfile: Dockerfile.tensorflow-gpu-jpyter
      target: base
    volumes:
      - /home/manishb/setup/ssh-server-setup/containers/tjg-1-manish/notebooks:/notebooks
      - /home/manishb/setup/ssh-server-setup/containers/tjg-1-manish/config:/config
    command:
      - /bin/sh
      - -c
      - |
        echo "Starting docker-compose's tensorflow-jupyter-gpu"
        # nvidia-smi
        jupyter notebook --config=/config/jupyter_notebook_config --ip 0.0.0.0

    environment:
      ##### run time###############
      TEST_ENV_VAR: ${TEST_ENV_VAR}
      NVIDIA_VISIBLE_DEVICES: all
    ports:
      - 1234:1234
    networks:
      - webnet
    restart: always
    # tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  #######
  tensorflow-jupyter-gpu-niten:
    container_name: tjg-2-niten
    build:
      context: .
      dockerfile: Dockerfile.tensorflow-gpu-jpyter
      target: base
    volumes:
      - /home/nitenl/setup/ssh-server-setup/containers/tjg-2-niten/notebooks:/notebooks
      - /home/nitenl/setup/ssh-server-setup/containers/tjg-2-niten/config:/config
    command:
      - /bin/sh
      - -c
      - |
        echo "Starting docker-compose's tensorflow-jupyter-gpu"
        # nvidia-smi
        jupyter notebook --config=/config/jupyter_notebook_config --ip 0.0.0.0

    environment:
      ##### run time###############
      TEST_ENV_VAR: ${TEST_ENV_VAR}
      NVIDIA_VISIBLE_DEVICES: all
    ports:
      - 60000:60000
    networks:
      - webnet
    restart: always
    # tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  ######
  tensorflow-jupyter-gpu-gaurab:
    container_name: tjg-3-gaurab
    build:
      context: .
      dockerfile: Dockerfile.tensorflow-gpu-jpyter
      target: base
    volumes:
      - /home/gaurabs/setup/ssh-server-setup/containers/tjg-3-gaurab/notebooks:/notebooks
      - /home/gaurabs/setup/ssh-server-setup/containers/tjg-3-gaurab/config:/config
    command:
      - /bin/sh
      - -c
      - |
        echo "Starting docker-compose's tensorflow-jupyter-gpu"
        # nvidia-smi
        jupyter notebook --config=/config/jupyter_notebook_config --ip 0.0.0.0

    environment:
      ##### run time###############
      TEST_ENV_VAR: ${TEST_ENV_VAR}
      NVIDIA_VISIBLE_DEVICES: all
    ports:
      - 1236:1236
    networks:
      - webnet
    restart: always
    # tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  ########
  tensorflow-jupyter-gpu-subash:
    container_name: tjg-4-subash
    build:
      context: .
      dockerfile: Dockerfile.tensorflow-gpu-jpyter
      target: base
    volumes:
      - /home/subashs/setup/ssh-server-setup/containers/tjg-4-subash/notebooks:/notebooks
      - /home/subashs/setup/ssh-server-setup/containers/tjg-4-subash/config:/config
    command:
      - /bin/sh
      - -c
      - |
        echo "Starting docker-compose's tensorflow-jupyter-gpu"
        # nvidia-smi
        jupyter notebook --config=/config/jupyter_notebook_config --ip 0.0.0.0

    environment:
      ##### run time###############
      TEST_ENV_VAR: ${TEST_ENV_VAR}
      NVIDIA_VISIBLE_DEVICES: all
    ports:
      - 1237:1237
    networks:
      - webnet
    restart: always
    # tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  ########

  tensorflow-jupyter-gpu-bijaya:
    container_name: tjg-5-bijaya
    build:
      context: .
      dockerfile: Dockerfile.tensorflow-gpu-jpyter
      target: base
    volumes:
      - /home/bijayd/setup/ssh-server-setup/containers/tjg-5-bijaya//notebooks:/notebooks
      - /home/bijayd/setup/ssh-server-setup/containers/tjg-5-bijaya//config:/config
    command:
      - /bin/sh
      - -c
      - |
        echo "Starting docker-compose's tensorflow-jupyter-gpu"
        # nvidia-smi
        jupyter notebook --config=/config/jupyter_notebook_config --ip 0.0.0.0

    environment:
      ##### run time###############
      TEST_ENV_VAR: ${TEST_ENV_VAR}
      NVIDIA_VISIBLE_DEVICES: all
    ports:
      - 1238:1238
    networks:
      - webnet
    restart: always
    # tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  ########

  tensorflow-jupyter-gpu-roshan:
    container_name: tjg-6-roshan
    build:
      context: .
      dockerfile: Dockerfile.tensorflow-gpu-jpyter
      target: base
    volumes:
      - /home/roshans/setup/ssh-server-setup/containers/tjg-6-roshan/notebooks:/notebooks
      - /home/roshans/setup/ssh-server-setup/containers/tjg-6-roshan/config:/config
    command:
      - /bin/sh
      - -c
      - |
        echo "Starting docker-compose's tensorflow-jupyter-gpu"
        # nvidia-smi
        jupyter notebook --config=/config/jupyter_notebook_config --ip 0.0.0.0

    environment:
      ##### run time###############
      TEST_ENV_VAR: ${TEST_ENV_VAR}
      NVIDIA_VISIBLE_DEVICES: all
    ports:
      - 1239:1239
    networks:
      - webnet
    restart: always
    # tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  ########

  tensorflow-jupyter-gpu-prakash:
    container_name: tjg-7-prakash
    build:
      context: .
      dockerfile: Dockerfile.tensorflow-gpu-jpyter
      target: base
    volumes:
      - /home/prakashd/setup/ssh-server-setup/containers/tjg-7-prakash/notebooks:/notebooks
      - /home/prakashd/setup/ssh-server-setup/containers/tjg-7-prakash/config:/config
    command:
      - /bin/sh
      - -c
      - |
        echo "Starting docker-compose's tensorflow-jupyter-gpu"
        # nvidia-smi
        jupyter notebook --config=/config/jupyter_notebook_config --ip 0.0.0.0

    environment:
      ##### run time###############
      TEST_ENV_VAR: ${TEST_ENV_VAR}
      NVIDIA_VISIBLE_DEVICES: all
    ports:
      - 1240:1240
    networks:
      - webnet
    restart: always
    # tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  ########

  tensorflow-jupyter-gpu-bigyan:
    container_name: tjg-8-bigyan
    build:
      context: .
      dockerfile: Dockerfile.tensorflow-gpu-jpyter
      target: base
    shm_size: "2gb"
    volumes:
      - /home/bigyans/setup/ssh-server-setup/containers/tjg-8-bigyan/notebooks:/notebooks
      - /home/bigyans/setup/ssh-server-setup/containers/tjg-8-bigyan/config:/config
    command:
      - /bin/sh
      - -c
      - |
        echo "Starting docker-compose's tensorflow-jupyter-gpu"
        # nvidia-smi
        jupyter notebook --config=/config/jupyter_notebook_config --ip 0.0.0.0

    environment:
      ##### run time###############
      TEST_ENV_VAR: ${TEST_ENV_VAR}
      NVIDIA_VISIBLE_DEVICES: all
    ports:
      - 1241:1241
    networks:
      - webnet
    restart: always
    # tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  ########

  tensorflow-jupyter-gpu-sagar:
    container_name: tjg-9-sagar
    build:
      context: .
      dockerfile: Dockerfile.tensorflow-gpu-jpyter
      target: base
    volumes:
      - /home/sagara/setup/ssh-server-setup/containers/tjg-9-sagar/notebooks:/notebooks
      - /home/sagara/setup/ssh-server-setup/containers/tjg-9-sagar/config:/config
    command:
      - /bin/sh
      - -c
      - |
        echo "Starting docker-compose's tensorflow-jupyter-gpu"
        # nvidia-smi
        jupyter notebook --config=/config/jupyter_notebook_config --ip 0.0.0.0

    environment:
      ##### run time###############
      TEST_ENV_VAR: ${TEST_ENV_VAR}
      NVIDIA_VISIBLE_DEVICES: all
    ports:
      - 1242:1242
    networks:
      - webnet
    restart: always
    # tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  ########

  tensorflow-jupyter-gpu-rk:
    container_name: tjg-10-rk
    build:
      context: .
      dockerfile: Dockerfile.tensorflow-gpu-jpyter
      target: base
    volumes:
      - /home/rkl/setup/ssh-server-setup/containers/tjg-10-rk/notebooks:/notebooks
      - /home/rkl/setup/ssh-server-setup/containers/tjg-10-rk/config:/config
    command:
      - /bin/sh
      - -c
      - |
        echo "Starting docker-compose's tensorflow-jupyter-gpu"
        # nvidia-smi
        jupyter notebook --config=/config/jupyter_notebook_config --ip 0.0.0.0

    environment:
      ##### run time###############
      TEST_ENV_VAR: ${TEST_ENV_VAR}
      NVIDIA_VISIBLE_DEVICES: all
    ports:
      - 1243:1243
    networks:
      - webnet
    restart: always
    # tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  ########

  tensorflow-jupyter-gpu-jabir:
    container_name: tjg-11-jabir
    build:
      context: .
      dockerfile: Dockerfile.tensorflow-gpu-jpyter
      target: base
    volumes:
      - /home/jabirk/setup/ssh-server-setup/containers/tjg-11-jabir/notebooks:/notebooks
      - /home/jabirk/setup/ssh-server-setup/containers/tjg-11-jabir/config:/config
    command:
      - /bin/sh
      - -c
      - |
        echo "Starting docker-compose's tensorflow-jupyter-gpu"
        # nvidia-smi
        jupyter notebook --config=/config/jupyter_notebook_config --ip 0.0.0.0

    environment:
      ##### run time###############
      TEST_ENV_VAR: ${TEST_ENV_VAR}
      NVIDIA_VISIBLE_DEVICES: all
    ports:
      - 1244:1244
    networks:
      - webnet
    restart: always
    # tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  ########

  tensorflow-jupyter-gpu-raghib:
    container_name: tjg-12-raghib
    build:
      context: .
      dockerfile: Dockerfile.tensorflow-gpu-jpyter
      target: base
    volumes:
      - /home/raghibi/setup/ssh-server-setup/containers/tjg-12-raghib/notebooks:/notebooks
      - /home/raghibi/setup/ssh-server-setup/containers/tjg-12-raghib/config:/config
    command:
      - /bin/sh
      - -c
      - |
        echo "Starting docker-compose's tensorflow-jupyter-gpu"
        # nvidia-smi
        jupyter notebook --config=/config/jupyter_notebook_config --ip 0.0.0.0

    environment:
      ##### run time###############
      TEST_ENV_VAR: ${TEST_ENV_VAR}
      NVIDIA_VISIBLE_DEVICES: all
    ports:
      - 1245:1245
    networks:
      - webnet
    restart: always
    # tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  ########

  tensorflow-jupyter-gpu-ashish:
    container_name: tjg-13-ashish
    build:
      context: .
      dockerfile: Dockerfile.tensorflow-gpu-jpyter
      target: base
    volumes:
      - /home/ashishs/setup/ssh-server-setup/containers/tjg-13-ashish/notebooks:/notebooks
      - /home/ashishs/setup/ssh-server-setup/containers/tjg-13-ashish/config:/config
    command:
      - /bin/sh
      - -c
      - |
        echo "Starting docker-compose's tensorflow-jupyter-gpu"
        # nvidia-smi
        jupyter notebook --config=/config/jupyter_notebook_config --ip 0.0.0.0

    environment:
      ##### run time###############
      TEST_ENV_VAR: ${TEST_ENV_VAR}
      NVIDIA_VISIBLE_DEVICES: all
    ports:
      - 1246:1246
    networks:
      - webnet
    restart: always
    # tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  ########

  tensorflow-jupyter-gpu-sangam:
    container_name: tjg-14-sangam
    build:
      context: .
      dockerfile: Dockerfile.tensorflow-gpu-jpyter
      target: base
    volumes:
      - /home/sangamb/setup/ssh-server-setup/containers/tjg-14-sangam/notebooks:/notebooks
      - /home/sangamb/setup/ssh-server-setup/containers/tjg-14-sangam/config:/config
    command:
      - /bin/sh
      - -c
      - |
        echo "Starting docker-compose's tensorflow-jupyter-gpu"
        # nvidia-smi
        jupyter notebook --config=/config/jupyter_notebook_config --ip 0.0.0.0

    environment:
      ##### run time###############
      TEST_ENV_VAR: ${TEST_ENV_VAR}
      NVIDIA_VISIBLE_DEVICES: all
    ports:
      - 60001:60001
    networks:
      - webnet
    restart: always
    # tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
########

############################################## Non GPU Nightly containers##############################################################
# tensorflow-nightly-jupyter-1:
#   container_name: tnj-1
#   build:
#     context: .
#     dockerfile: Dockerfile.nightly-jupyter
#     target: base
#     args:
#       PORT: ${BIGYAN_PORT}
#   volumes:
#     - ./containers/tnj-1/notebooks:/notebooks
#     - ./containers/tnj-1/config:/config
#     # - ./tailfile.txt:/setup/tailfile.txt
#   # tty: true
#   command:
#     - /bin/bash
#     - -c
#     - |
#       echo "Starting docker-compose's tensorflow-nightly-jupyter"
#       # jupyter notebook --notebook-dir=/notebooks --ip 0.0.0.0 --no-browser --allow-root

#       # export JUPYTER_CONFIG_DIR=/config
#       # jupyter notebook --generate-config

#       jupyter notebook --config=/config/jupyter_notebook_config --ip 0.0.0.0

#       # tail -F tailfile.txt
#   environment:
#     ##### run time###############
#     TEST_ENV_VAR: ${TEST_ENV_VAR}
#   ports:
#     - 1235:1235
#   networks:
#     - webnet
#   restart: always

# tensorflow-nightly-jupyter-2:
#   container_name: tnj-2
#   build:
#     context: .
#     dockerfile: Dockerfile.nightly-jupyter
#     target: base
#   volumes:
#     - ./containers/tnj-2/notebooks:/notebooks
#     - ./containers/tnj-2/config:/config
#     # - ./tailfile.txt:/setup/tailfile.txt
#   # tty: true
#   command:
#     - /bin/bash
#     - -c
#     - |
#       echo "Starting docker-compose's tensorflow-nightly-jupyter"
#       # jupyter notebook --notebook-dir=/notebooks --ip 0.0.0.0 --no-browser --allow-root

#       # export JUPYTER_CONFIG_DIR=/config
#       # jupyter notebook --generate-config

#       jupyter notebook --config=/config/jupyter_notebook_config --ip 0.0.0.0

#       # tail -F tailfile.txt
#   environment:
#     ##### run time###############
#     TEST_ENV_VAR: ${TEST_ENV_VAR}
#   ports:
#     - 1236:1236
#   networks:
#     - webnet
#   restart: always

networks:
  webnet:

volumes:
  data-configs:
    driver: local
  data-server:
