version: '3.7'

services:

  tensorflow-jupyter-gpu:
    container_name: tjg-1
    build:
      context: .
      dockerfile: Dockerfile.tensorflow-gpu-jpyter   
      target: base
    volumes:
      - ./notebooks/tjg-1:/tf
    command:
      - /bin/sh
      - -c
      - |
        echo "Starting docker-compose's tensorflow-jupyter-gpu"
        nvidia-smi
        jupyter notebook --notebook-dir=/tf --ip 0.0.0.0 --no-browser --allow-root
        
    environment:
      ##### run time ###############
      TEST_ENV_VAR: ${TEST_ENV_VAR}
      NVIDIA_VISIBLE_DEVICES: all
    ports:
      - 1234:8888 
    networks:
      - webnet
    restart: always
    # tty: true
    deploy:
      resources:
        reservations:
          devices:
          -  driver: nvidia
             count: all
             capabilities: [gpu]


  tensorflow-nightly-jupyter:
    container_name: tnj-1
    build:
      context: .
      dockerfile: Dockerfile.nightly-jupyter
      target: base
    # volumes: 
    #   - ./notebooks:/notebooks  
    #   - ./tailfile.txt:/setup/tailfile.txt
    command:
      - /bin/sh
      - -c
      - |
        echo "Starting docker-compose's tensorflow-nightly-jupyter"
        jupyter notebook --ip 0.0.0.0 . --allow-root

    environment:
      ##### run time ###############
      TEST_ENV_VAR: ${TEST_ENV_VAR}
    ports:
      - 1235:8888 
    networks:
      - webnet
    restart: always



  # datascience-notebook:
  #   image: jupyter/tensorflow-notebook
  #   container_name: tn-1
  #   # volumes:
  #   #   - </path/to/local/project/files>:/home/jovyan/work
  #   ports:
  #     - 8888:8888
  #   networks:
  #     - webnet
  #   restart: always


networks:
  webnet:

volumes:
  pgadmin-configs:
    driver: local
  pgdata-server: